## Day 33 Lecture 2 Assignment

In this assignment, we will learn about non linear SVM models. We will use the heart disease dataset loaded below and analyze the model generated for this dataset.

In [0]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [0]:
heart = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/framingham_heart_disease.csv')

In [0]:
heart.shape

(4238, 16)

In [0]:
heart.head()

male  age  education  currentSmoker  ...    BMI  heartRate  glucose  TenYearCHD
0     1   39        4.0              0  ...  26.97       80.0     77.0           0
1     0   46        2.0              0  ...  28.73       95.0     76.0           0
2     1   48        1.0              1  ...  25.34       75.0     70.0           0
3     0   61        3.0              1  ...  28.58       65.0    103.0           1
4     0   46        3.0              1  ...  23.10       85.0     85.0           0

[5 rows x 16 columns]

This dataset helps us predict the probability of coronary heart diease (CHD) in the next 10 years given the risk factors for each subject in the study. Our target variable is `TenYearCHD`.

We'll start off by removing any rows containing missing data.

In [0]:
# answer below:

hcl = heart.dropna()
hcl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3656 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             3656 non-null   int64  
 1   age              3656 non-null   int64  
 2   education        3656 non-null   float64
 3   currentSmoker    3656 non-null   int64  
 4   cigsPerDay       3656 non-null   float64
 5   BPMeds           3656 non-null   float64
 6   prevalentStroke  3656 non-null   int64  
 7   prevalentHyp     3656 non-null   int64  
 8   diabetes         3656 non-null   int64  
 9   totChol          3656 non-null   float64
 10  sysBP            3656 non-null   float64
 11  diaBP            3656 non-null   float64
 12  BMI              3656 non-null   float64
 13  heartRate        3656 non-null   float64
 14  glucose          3656 non-null   float64
 15  TenYearCHD       3656 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 485.6 KB


Then, we split the data into train and test with 20% of the data in the test subset.

In [0]:
# answer below:
from sklearn.model_selection import train_test_split
X = hcl.drop('TenYearCHD', axis =1)
y = hcl['TenYearCHD']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
X

male  age  education  currentSmoker  ...  diaBP    BMI  heartRate  glucose
0        1   39        4.0              0  ...   70.0  26.97       80.0     77.0
1        0   46        2.0              0  ...   81.0  28.73       95.0     76.0
2        1   48        1.0              1  ...   80.0  25.34       75.0     70.0
3        0   61        3.0              1  ...   95.0  28.58       65.0    103.0
4        0   46        3.0              1  ...   84.0  23.10       85.0     85.0
...    ...  ...        ...            ...  ...    ...    ...        ...      ...
4231     1   58        3.0              0  ...   81.0  24.96       80.0     81.0
4232     1   68        1.0              0  ...   97.0  23.14       60.0     79.0
4233     1   50        1.0              1  ...   92.0  25.97       66.0     86.0
4234     1   51        3.0              1  ...   80.0  19.71       65.0     68.0
4237     0   52        2.0              0  ...   83.0  21.47       80.0    107.0

[3656 rows x 15 columns]

We will then scale the data using the standard scaler. Do this in the cell below.

In [0]:
# answer below:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(X_train)


array([[ 1.12234574, -1.81330331,  0.97666516, ..., -0.56504548,
         0.76689697, -0.70834214],
       [ 1.12234574, -0.76430595,  0.97666516, ..., -0.39414799,
        -0.87914777,  0.90146972],
       [-0.89099104,  1.5667993 , -0.9666958 , ...,  3.25817551,
         0.19078131, -0.11525356],
       ...,
       [ 1.12234574,  2.03302035, -0.9666958 , ...,  0.21620019,
         0.76689697, -0.32707091],
       [-0.89099104,  0.6343572 ,  0.97666516, ...,  0.29920754,
        -0.30303211, -0.11525356],
       [-0.89099104, -0.53119543, -0.9666958 , ...,  0.46522224,
         1.17840816, -0.15761703]])

In [0]:
# We would like to compare the runtime of a number of functions later in our code. 
import time
start_time = time.time()
main()
print("--- %s seconds ---" % (time.time() - start_time))


NameError: ignored

Generate a polynomial SVC model and a RBF SVC model. Compare the scores for the two models (train and test) and also compare the runtime of the two models.

In [0]:
# answer below:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC

clf = SVC(kernel='poly', C=1000)
SVC()
clf.fit(X_train, y_train)

y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)

print(accuracy_score(y_test, y_pred_test))
print(accuracy_score(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

0.8456284153005464
0.850547195622435


array([[2481,    0],
       [ 437,    6]])

In [0]:
clfrbf = SVC(kernel='rbf', C=1000, gamma = 'scale')
SVC()
clfrbf.fit(X_train, y_train)

y_pred_train = clfrbf.predict(X_train)
y_pred_test = clfrbf.predict(X_test)

print(accuracy_score(y_test, y_pred_test))
print(accuracy_score(y_train, y_pred_train))
confusion_matrix(y_train, y_pred_train)

0.8483606557377049
0.853967168262654


array([[2481,    0],
       [ 427,   16]])

Which model overfits more? Why? How would you improve the model that overfits more?

In [0]:
# answer below:

